




<field:type itemname="device type" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:type>

<field:brand itemname="brand" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:brand>

<field:model itemname="model" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:model>

<field:fault itemname="fault" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:fault>

<field:name itemname="name" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:email itemname="email" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:number itemname="number" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:number>
