<?php
$z[0]=Array("type","\r\n",8,134);
$z[0][4]['itemname']="device type";
$z[0][4]['autofield']="1";
$z[0][4]['type']="text";
$z[0][4]['isnull']="true";
$z[0][4]['default']="";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("brand","\r\n",137,259);
$z[1][4]['itemname']="brand";
$z[1][4]['autofield']="1";
$z[1][4]['type']="text";
$z[1][4]['isnull']="true";
$z[1][4]['default']="";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";

?>