
<field:company itemname="Company" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>



<field:name itemname="Name" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>



<field:telephone itemname="Telephone" autofield="1" type="textchar" isnull="true" default=""  maxlength="250" page="">
</field:telephone>



<field:cellphone itemname="Cellphone" autofield="1" type="text" isnull="true" default=""  maxlength="15" page="">
</field:cellphone>


<field:email itemname="Email" autofield="1" type="text" isnull="true" default=""  maxlength="50" page="">
</field:email>


<field:address itemname="Address" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:address>


<field:knowus itemname="know us" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:knowus>

<field:joinus itemname="join us" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:joinus>
