
<field:company itemname="公司名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:name itemname="申请人名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:telephone itemname="telephone" autofield="1" type="int" isnull="true" default=""  maxlength="250" page="">
</field:telephone>

<field:cellphone itemname="cellphone手机" autofield="1" type="text" isnull="true" default=""  maxlength="15" page="">
</field:cellphone>

<field:email itemname="email" autofield="1" type="text" isnull="true" default=""  maxlength="50" page="">
</field:email>
