
<field:company itemname="company" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>


<field:name itemname="name" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>


<field:telephone itemname="telephone" autofield="1" type="textchar" isnull="true" default=""  maxlength="250" page="">
</field:telephone>


<field:cellphone itemname="Cellphone" autofield="1" type="text" isnull="true" default=""  maxlength="15" page="">
</field:cellphone>


<field:email itemname="email" autofield="1" type="text" isnull="true" default=""  maxlength="50" page="">
</field:email>

<field:address itemname="address" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:address>

<field:knowus itemname="know us" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:knowus>

<field:joinus itemname="join us" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:joinus>
